package com.aisino.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2017-02-03T14:07:27.514+08:00
 * Generated source version: 3.0.10
 */
@WebService(targetNamespace = "http://com.aisino.web/", name = "DispatcherController")
public interface IEI51TransferServiceUpProService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "billingServiceInterface", targetNamespace = "http://com.aisino.web/", className = "web.aisino.com.BillingServiceInterface")
    @WebMethod
    @ResponseWrapper(localName = "billingServiceInterfaceResponse", targetNamespace = "http://com.aisino.web/", className = "web.aisino.com.BillingServiceInterfaceResponse")
    public String billingServiceInterface(
            @WebParam(name = "envelope", targetNamespace = "http://com.aisino.web/")
                    String envelope,
            @WebParam(name = "option", targetNamespace = "http://com.aisino.web/")
                    String option
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "eiInterface", targetNamespace = "http://com.aisino.web/", className = "web.aisino.com.EiInterface")
    @WebMethod
    @ResponseWrapper(localName = "eiInterfaceResponse", targetNamespace = "http://com.aisino.web/", className = "web.aisino.com.EiInterfaceResponse")
    public String eiInterface(
            @WebParam(name = "envelope", targetNamespace = "http://com.aisino.web/")
                    String envelope
    );
}
