package com.aisino.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-07-13T14:06:37.614+08:00
 * Generated source version: 2.7.18
 */
@WebService(targetNamespace = "http://ws.aisino.com", name = "IEInvWebService")
public interface IEIfpqzService {

    @WebResult(name = "return", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "eiInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.EiInterface")
    @WebMethod
    @ResponseWrapper(localName = "eiInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.EiInterfaceResponse")
    public String eiInterface(
            @WebParam(name = "requestDownLoadXML", targetNamespace = "http://ws.aisino.com")
                    String requestDownLoadXML
    );
}
