package com.aisino.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2017-03-14T09:46:07.942+08:00
 * Generated source version: 3.0.10
 */
@WebService(targetNamespace = "http://impl.ws.aisino.com/", name = "IEInvWebService")
public interface IEInvzzsslService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "eiInterface", targetNamespace = "http://impl.ws.aisino.com/", className = "com.aisino.ws.impl.EiInterface")
    @WebMethod
    @ResponseWrapper(localName = "eiInterfaceResponse", targetNamespace = "http://impl.ws.aisino.com/", className = "com.aisino.ws.impl.EiInterfaceResponse")
    public String eiInterface(
            @WebParam(name = "requestMessage", targetNamespace = "http://impl.ws.aisino.com/")
                    String requestMessage
    );
}
