package com.aisino.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2016-08-16T17:44:39.636+08:00
 * Generated source version: 3.0.10
 */
@WebService(targetNamespace = "http://ws.aisino.com", name = "IEInvWebServicePortType")
public interface IEIzzs_kpfwService {

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "fpkccxInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.FpkccxInterface")
    @WebMethod
    @ResponseWrapper(localName = "fpkccxInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.FpkccxInterfaceResponse")
    public String fpkccxInterface(
            @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "eiInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.EiInterface")
    @WebMethod
    @ResponseWrapper(localName = "eiInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.EiInterfaceResponse")
    public String eiInterface(
            @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "djxxcxInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.DjxxcxInterface")
    @WebMethod
    @ResponseWrapper(localName = "djxxcxInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.DjxxcxInterfaceResponse")
    public String djxxcxInterface();

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "fpkjInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.FpkjInterface")
    @WebMethod
    @ResponseWrapper(localName = "fpkjInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.FpkjInterfaceResponse")
    public String fpkjInterface(
            @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
                    String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "fpcyInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.FpcyInterface")
    @WebMethod
    @ResponseWrapper(localName = "fpcyInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.FpcyInterfaceResponse")
    public String fpcyInterface(
            @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
                    String in0
    );
}
